version: "3"
services:
  reverse-proxy:
    image: nginx:stable
    restart: unless-stopped
    depends_on:
      - app
      - db
    volumes:
      - ./nginx:/etc/nginx/
    ports:
      - "8080:80"
  app:
    image: hugelifts:latest
    restart: unless-stopped
    expose:
      - "3000"
    depends_on:
      - db
    env_file:
      - app.env
  db:
    image: postgres:11
    restart: unless-stopped
    expose:
      - "5432"
    env_file:
      - db.env
    volumes:
      - ./tmp/db:/var/lib/postgresql/data