version: '3'
services:
  db:
    image: postgres:11
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'docker'
      POSTGRES_PASSWORD: 'docker'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  loki:
    image: grafana/loki:2.6.1
    ports:
      - "3100"
    volumes:
      - ./volumes/loki:/loki
  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - ./config/promtail.yml:/etc/promtail/config.yml
      - ./log:/app/log
  grafana:
    image: grafana/grafana:9.2.2
    ports:
      - "5000:3000"
    volumes:
      - ./volumes/grafana:/var/lib/grafana
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/