version: "3"
services:
  reverse-proxy:
    image: nginx:stable
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - app
      - db
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
  app:
    image: hugelifts:latest
    restart: unless-stopped
    expose:
      - "3000"
    depends_on:
      - db
    env_file:
      - app.env
    volumes:
      - ./log:/app/log
  db:
    image: postgres:11
    restart: unless-stopped
    expose:
      - "5432"
    env_file:
      - db.env
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  loki:
    image: grafana/loki:2.6.1
    expose:
      - "3100"
    volumes:
      - ./volumes/loki:/loki
  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - ./config/promtail.yml:/etc/promtail/config.yml
      - ./log:/app/log
  grafana:
    image: grafana/grafana:9.2.2
    expose:
      - "3000"
    env_file:
      - grafana.env
    volumes:
      - ./volumes/grafana:/var/lib/grafana
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/