version: '3'
services:
  db:
    image: postgres:11
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'docker'
      POSTGRES_PASSWORD: 'docker'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  app:
    image: hugelifts:latest
    restart: unless-stopped
    environment:
      WAIT_HOSTS: 'db:5432'
      WAIT_BEFORE_HOSTS: 10
    env_file:
      - docker.app.env # RAILS_MASTER_KEY=..., HUGELIFTS_DATABASE_PASSWORD=...
    depends_on:
      - db
    ports:
      - '3000:3000'