version: "3"
services:
  reverse-proxy:
    image: nginx:stable
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - app
      - db
    volumes:
      - ./nginx:/etc/nginx/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "8080:80"
  app:
    image: hugelifts:latest
    restart: unless-stopped
    expose:
      - "3000"
    depends_on:
      - db
    env_file:
      - app.env
  db:
    image: postgres:11
    restart: unless-stopped
    expose:
      - "5432"
    env_file:
      - db.env
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot