groups:
  - name: LokiAlerts
    rules:
      - alert: ErrorOccurred
        expr: |
          sum by (job)
            (rate({job="hugelifts"} |= `ERROR`[2m]))
            > 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 2 minutes."
