apiVersion: 1

datasources:
  - name: Loki
    type: loki
    url: http://loki:3100

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    graphiteVersion: "1.1"
    tlsAuth: false
    tlsAuthWithCACert: false
    version: 1
    editable: true